name: PR • Run external Python script

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read


jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout external script repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/ci-external-scripts
          ref: main
          path: ext

      - name: Run script (posts PR comment)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python testing/py_script.py
